### ISSUE TITLE
Error in profiles.yml

### ISSUE THREAD

**Issue by stevenhurwitt** [josephmachado/simple_dbt_project#2]
When creating my profiles.yml it looks like `dbt debug` doesn't like the schema entry, `dbt`_tutorial. My file looks like this:

```
tutorial:
  outputs:
    dev:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: steven
      password: ***
      dbname: tutorial
      schema: `dbt`_tutorial

  target: dev
```

and for the schema, it looks like the first ` symbol doesn't light up orange in vs code. Is this a legal yaml first-character? Getting this error btw:

```
Runtime Error
    Syntax error near line 11
    ------------------------------
    8  |       user: steven
    9  |       password: ***
    10 |       dbname: tutorial
    11 |       schema: `dbt`_tutorial
    12 |
    13 |   target: dev
    14 |

    Raw Error:
    ------------------------------
    while scanning for the next token
    found character that cannot start any token
      in "<unicode string>", line 11, column 15
```
